# Service for Streamlit UI Application
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-tpetkos-sample01
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-tpetkos-sample01
  name: test-tpetkos-sample01
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
      name: http
  selector:
    app.kubernetes.io/instance: test-tpetkos-sample01

